const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const vm = require('node:vm');
const { execFileSync } = require('node:child_process');

// The Railway Docker build runs scripts/patch-provider-routing.mjs as a
// fail-closed verifier. Run it against an isolated copy of the committed source
// so this test exercises exactly what Docker deploys, then drive the audio route
// in a VM with faked providers.
const root = path.resolve(__dirname, '../..');
const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'studio-routing-test-'));
test.after(() => fs.rmSync(fixture, { recursive: true, force: true }));
for (const file of ['backend/server.js', 'backend/services/videoGenerationOrchestrator.js']) {
  fs.mkdirSync(path.dirname(path.join(fixture, file)), { recursive: true });
  fs.copyFileSync(path.join(root, file), path.join(fixture, file));
}
execFileSync(process.execPath, [path.join(root, 'scripts/patch-provider-routing.mjs'), fixture]);
const deployed = fs.readFileSync(path.join(fixture, 'backend/server.js'), 'utf8');
const start = deployed.indexOf("app.post('/api/generate-audio'");
const end = deployed.indexOf("app.post('/api/mix-audio'", start);

async function generate(body, { env, balance = { ok: true, status: 200, credits: 500 }, stability } = {}) {
  let handler;
  let result;
  let status = 200;
  let refunds = 0;
  const models = [];
  const stabilityCalls = [];
  const stabilityBehaviour = stability || (() => ({ ok: true, status: 200 }));
  const context = {
    app: { post: (...args) => { handler = args.at(-1); } },
    verifyFirebaseToken() {}, requireAuthOrFreeLimit() {}, generationLimiter() {},
    checkCreditsFor: () => () => {},
    process: { env: env || { STABILITY_API_KEY: 'test-only', REPLICATE_API_KEY: 'test-only', FAL_KEY: 'test-only' } },
    logger: { info() {}, warn() {}, error() {} },
    getStabilityAudioSettings: () => ({ model: 'stable-audio-2.5', steps: 8, cfgScale: null }),
    buildBeatGenerationPrompt: () => 'Original test instrumental',
    readStabilityAudioResponse: async () => 'data:audio/mpeg;base64,' + Buffer.alloc(2000, 1).toString('base64'),
    Replicate: class {}, Buffer, AbortSignal, FormData, Blob,
    globalThis: {},
    fetch: async () => ({ ok: balance.ok, status: balance.status, json: async () => ({ credits: balance.credits }) }),
    fetchWithRetry: async (url, options) => {
      if (String(url).includes('api.stability.ai')) {
        const endpoint = String(url).split('/').at(-1);
        stabilityCalls.push({ endpoint, form: options.body });
        const outcome = stabilityBehaviour(endpoint);
        return { ok: outcome.ok, status: outcome.status, json: async () => (outcome.body || {}) };
      }
      return {
        ok: true,
        status: 200,
        headers: { get: () => 'audio/wav' },
        arrayBuffer: async () => Buffer.alloc(5000, 7)
      };
    },
    runReplicateWithRateLimitRetry: async (_client, model) => {
      models.push(model);
      return 'https://example.test/test-fixture.mp3';
    },
    refundCredits: async () => { refunds++; },
    safeErrorDetail: error => error.message,
  };
  vm.runInNewContext(deployed.slice(start, end), context);
  await handler({ body }, {
    status(code) { status = code; return this; },
    json(payload) { result = payload; return this; },
  });
  return { status, result, models, stabilityCalls, refunds };
}

// Product policy: every beat is a full-length 90–150s track. Shorter or longer
// requests are clamped server-side so stale clients cannot produce clips.
for (const [duration, expected] of [[30, 90], [60, 90], [120, 120], [180, 150]]) {
  test(`deployed ${duration}s request is generated by Stability only at ${expected}s`, async () => {
    const outcome = await generate({ prompt: 'Original instrumental', quality: 'premium', duration });
    assert.equal(outcome.status, 200, JSON.stringify(outcome.result));
    assert.deepEqual(outcome.models, [], 'No Replicate model may run while Stability is configured');
    assert.deepEqual(outcome.stabilityCalls.map(c => c.endpoint), ['text-to-audio']);
    assert.equal(outcome.stabilityCalls[0].form.get('duration'), String(expected));
    assert.equal(outcome.result.provider, 'stable-audio-2.5');
    assert.equal(outcome.result.requestedDuration, expected);
    assert.equal(outcome.result.isReleaseCandidate, true);
    assert.equal(outcome.refunds, 0);
  });
}

test('reference audio (Audio DNA) uses Stability audio-to-audio, never another engine', async () => {
  const outcome = await generate({
    prompt: 'Keep the reference groove',
    engine: 'auto',
    quality: 'premium',
    referenceAudio: 'https://example.test/reference.wav',
  });
  assert.equal(outcome.status, 200, JSON.stringify(outcome.result));
  assert.deepEqual(outcome.models, []);
  assert.deepEqual(outcome.stabilityCalls.map(c => c.endpoint), ['audio-to-audio']);
  assert.equal(outcome.stabilityCalls[0].form.get('strength'), '0.6');
  assert.ok(outcome.stabilityCalls[0].form.get('audio'), 'reference audio is attached to the form');
  assert.equal(outcome.result.provider, 'stable-audio-2.5');
  assert.equal(outcome.refunds, 0);
});

test('failed audio-to-audio pass falls back to Stability text-to-audio with the DNA prompt', async () => {
  const outcome = await generate(
    { prompt: 'Keep the reference groove', referenceAudio: 'https://example.test/reference.wav' },
    { stability: endpoint => (endpoint === 'audio-to-audio' ? { ok: false, status: 400, body: { message: 'bad reference' } } : { ok: true, status: 200 }) }
  );
  assert.equal(outcome.status, 200, JSON.stringify(outcome.result));
  assert.deepEqual(outcome.stabilityCalls.map(c => c.endpoint), ['audio-to-audio', 'text-to-audio']);
  assert.deepEqual(outcome.models, []);
  assert.equal(outcome.refunds, 0);
});

test('an explicit music-gpt engine request still lands on Stability', async () => {
  const outcome = await generate({ prompt: 'Original instrumental', engine: 'music-gpt' });
  assert.equal(outcome.status, 200, JSON.stringify(outcome.result));
  assert.deepEqual(outcome.models, []);
  assert.equal(outcome.result.provider, 'stable-audio-2.5');
});

test('exhausted Stability balance fails fast with a refund instead of swapping engines', async () => {
  const outcome = await generate(
    { prompt: 'Original instrumental', quality: 'premium', duration: 60 },
    { balance: { ok: true, status: 200, credits: -95 } }
  );
  assert.equal(outcome.status, 503, JSON.stringify(outcome.result));
  assert.equal(outcome.result.isSystemCreditIssue, true);
  assert.deepEqual(outcome.stabilityCalls, [], 'No paid Stability call is started');
  assert.deepEqual(outcome.models, [], 'No fallback engine runs');
  assert.equal(outcome.refunds, 1);
});

test('a failed balance probe does not block generation', async () => {
  const outcome = await generate(
    { prompt: 'Original instrumental' },
    { balance: { ok: false, status: 500, credits: undefined } }
  );
  assert.equal(outcome.status, 200, JSON.stringify(outcome.result));
  assert.equal(outcome.result.provider, 'stable-audio-2.5');
});

test('Stability provider failure is refunded and does not run legacy providers', async () => {
  const outcome = await generate(
    { prompt: 'Original instrumental' },
    { stability: () => ({ ok: false, status: 500, body: { message: 'upstream' } }) }
  );
  assert.equal(outcome.status, 500, JSON.stringify(outcome.result));
  assert.deepEqual(outcome.models, []);
  assert.equal(outcome.refunds, 1);
});

test('no configured audio provider returns an actionable 503 and refunds', async () => {
  const outcome = await generate({ prompt: 'Original instrumental' }, { env: { REPLICATE_API_KEY: 'test-only' } });
  assert.equal(outcome.status, 503, JSON.stringify(outcome.result));
  assert.equal(outcome.result.isProviderConfigIssue, true);
  assert.deepEqual(outcome.models, [], 'Replicate is never used for beats');
  assert.equal(outcome.refunds, 1);
});

test('legacy beat providers are gone: BEAT_FALLBACK_PROVIDERS has no effect', async () => {
  const outcome = await generate(
    { prompt: 'Original instrumental', duration: 60 },
    { env: { REPLICATE_API_KEY: 'test-only', FAL_KEY: 'test-only', BEAT_FALLBACK_PROVIDERS: 'true' } }
  );
  assert.equal(outcome.status, 503, JSON.stringify(outcome.result));
  assert.deepEqual(outcome.models, []);
  assert.equal(outcome.refunds, 1);
  const audioStart = deployed.indexOf("app.post('/api/generate-audio'");
  const audioEnd = deployed.indexOf("app.post('/api/mix-audio'", audioStart);
  const audioRoute = deployed.slice(audioStart, audioEnd);
  for (const forbidden of ['minimax/music', 'musicgen', 'beatoven', 'BEAT_FALLBACK_PROVIDERS', 'useLegacyBeatProviders']) {
    assert.ok(!audioRoute.includes(forbidden), `audio route must not reference ${forbidden}`);
  }
});

function providerHarness(status = 'succeeded', configuredTimeout) {
  const calls = [];
  const context = {
    process: { env: { REPLICATE_API_TOKEN: 'fixture-only', REPLICATE_GENERATION_TIMEOUT_MS: configuredTimeout } },
    logger: { info() {}, warn() {} },
    setTimeout: callback => callback(), Date,
    fetchWithTimeout: async (url, options) => {
      calls.push({ url, options });
      return { ok: true, status: 200, text: async () => JSON.stringify({ id: 'fixture', status, output: status === 'succeeded' ? 'fixture-output' : null }) };
    },
  };
  const helperStart = deployed.indexOf('async function runReplicateWithRateLimitRetry(');
  vm.runInNewContext(deployed.slice(helperStart, deployed.indexOf('const app = express()', helperStart)), context);
  return { calls, run: context.runReplicateWithRateLimitRetry };
}

for (const [operation, seconds] of [['MiniMax vocal generation', '150s'], ['MiniMax beat generation', '150s'], ['Musical vocal stem separation', '180s']]) {
  test(`deployed ${operation} has an explicit ${seconds} total budget`, async () => {
    const { calls, run } = providerHarness();
    await run(null, 'owner/model', { input: {} }, operation);
    assert.equal(calls[0].options.headers['Cancel-After'], seconds);
    assert.equal(calls.length, 1);
  });
}

test('an explicitly configured smaller provider budget remains respected', async () => {
  const { calls, run } = providerHarness('succeeded', '60000');
  await run(null, 'owner/model', { input: {} }, 'Musical vocal stem separation');
  assert.equal(calls[0].options.headers['Cancel-After'], '60s');
});

test('aborted provider prediction is terminal without polling or duplicate creation', async () => {
  const { calls, run } = providerHarness('aborted');
  await assert.rejects(run(null, 'owner/model', { input: {} }, 'Musical vocal stem separation'), { code: 'PROVIDER_FAILED' });
  assert.equal(calls.length, 1);
});
